"""WPD property keys and GUIDs, transcribed from the Windows SDK headers
``PortableDevice.h`` and ``WpdMtpExtensions.h``.
"""

from __future__ import annotations

from ._com import PROPERTYKEY

WPD_CATEGORY_COMMON = "{F0422A9C-5DC8-4440-B5BD-5DF28835658A}"
WPD_CATEGORY_MTP_EXT_VENDOR_OPERATIONS = "{4D545058-1A2E-4106-A357-771E0819FC56}"
_CLIENT = "{204D9F0C-2292-4080-9F42-40664E70F859}"

# Vendor-extended MTP device properties are surfaced by the Windows MTP driver
# under this format GUID, with the MTP property code as the PID.
WPD_PROPERTIES_MTP_VENDOR_EXTENDED_DEVICE_PROPS = "{4D545058-8900-40B3-8F1D-DC246E1E8370}"

WPD_PROPERTY_COMMON_COMMAND_CATEGORY = PROPERTYKEY(WPD_CATEGORY_COMMON, 1001)
WPD_PROPERTY_COMMON_COMMAND_ID = PROPERTYKEY(WPD_CATEGORY_COMMON, 1002)
WPD_PROPERTY_COMMON_HRESULT = PROPERTYKEY(WPD_CATEGORY_COMMON, 1003)

WPD_CLIENT_NAME = PROPERTYKEY(_CLIENT, 2)
WPD_CLIENT_MAJOR_VERSION = PROPERTYKEY(_CLIENT, 3)
WPD_CLIENT_MINOR_VERSION = PROPERTYKEY(_CLIENT, 4)
WPD_CLIENT_REVISION = PROPERTYKEY(_CLIENT, 5)
WPD_CLIENT_SECURITY_QUALITY_OF_SERVICE = PROPERTYKEY(_CLIENT, 8)
WPD_CLIENT_DESIRED_ACCESS = PROPERTYKEY(_CLIENT, 9)

# Command ids within WPD_CATEGORY_MTP_EXT_VENDOR_OPERATIONS.
CMD_GET_SUPPORTED_VENDOR_OPCODES = 11
CMD_EXECUTE_WITHOUT_DATA_PHASE = 12
CMD_EXECUTE_WITH_DATA_TO_READ = 13
CMD_EXECUTE_WITH_DATA_TO_WRITE = 14
CMD_READ_DATA = 15
CMD_WRITE_DATA = 16
CMD_END_DATA_TRANSFER = 17
CMD_GET_VENDOR_EXTENSION_DESCRIPTION = 18

_MTP = WPD_CATEGORY_MTP_EXT_VENDOR_OPERATIONS
WPD_PROPERTY_MTP_EXT_OPERATION_CODE = PROPERTYKEY(_MTP, 1001)
WPD_PROPERTY_MTP_EXT_OPERATION_PARAMS = PROPERTYKEY(_MTP, 1002)
WPD_PROPERTY_MTP_EXT_RESPONSE_CODE = PROPERTYKEY(_MTP, 1003)
WPD_PROPERTY_MTP_EXT_RESPONSE_PARAMS = PROPERTYKEY(_MTP, 1004)
WPD_PROPERTY_MTP_EXT_VENDOR_OPERATION_CODES = PROPERTYKEY(_MTP, 1005)
WPD_PROPERTY_MTP_EXT_TRANSFER_CONTEXT = PROPERTYKEY(_MTP, 1006)
WPD_PROPERTY_MTP_EXT_TRANSFER_TOTAL_DATA_SIZE = PROPERTYKEY(_MTP, 1007)
WPD_PROPERTY_MTP_EXT_TRANSFER_NUM_BYTES_TO_READ = PROPERTYKEY(_MTP, 1008)
WPD_PROPERTY_MTP_EXT_TRANSFER_NUM_BYTES_READ = PROPERTYKEY(_MTP, 1009)
WPD_PROPERTY_MTP_EXT_TRANSFER_NUM_BYTES_TO_WRITE = PROPERTYKEY(_MTP, 1010)
WPD_PROPERTY_MTP_EXT_TRANSFER_NUM_BYTES_WRITTEN = PROPERTYKEY(_MTP, 1011)
WPD_PROPERTY_MTP_EXT_TRANSFER_DATA = PROPERTYKEY(_MTP, 1012)
WPD_PROPERTY_MTP_EXT_OPTIMAL_TRANSFER_BUFFER_SIZE = PROPERTYKEY(_MTP, 1013)
WPD_PROPERTY_MTP_EXT_VENDOR_EXTENSION_DESCRIPTION = PROPERTYKEY(_MTP, 1014)

SECURITY_IMPERSONATION = 2
GENERIC_READ = 0x80000000
GENERIC_WRITE = 0x40000000
